#!/usr/bin/env python3
"""Build blog posts from blog/ into Jekyll format.

Scans blog/ for post folders, processes each post.md:
  - Adds Jekyll front matter (layout, permalink)
  - Rewrites image paths: images/X.png -> /assets/images/{slug}/X.png
  - Copies images/ -> assets/images/{slug}/
  - Writes processed post to _posts/YYYY-MM-DD-slug.md

Usage:
    python scripts/build.py
    python scripts/build.py --clean    # Also clean old generated files first
"""

import re
import shutil
import sys
import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "blog"
POSTS_DIR = REPO_ROOT / "_posts"
ASSETS_IMG_DIR = REPO_ROOT / "assets" / "images"


def parse_front_matter(content: str):
    """Extract YAML front matter and body from markdown content."""
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)", content, re.DOTALL)
    if not match:
        return {}, content
    yaml_str, body = match.groups()

    fm = {}
    for line in yaml_str.strip().splitlines():
        line = line.strip()
        if ":" in line:
            key, val = line.split(":", 1)
            val = val.strip().strip('"').strip("'")
            val = val.strip("[]")
            fm[key.strip()] = val
    return fm, body


def build_post(post_dir: Path):
    """Process a single blog post folder."""
    post_file = post_dir / "post.md"
    if not post_file.exists():
        print(f"  SKIP: {post_dir.name} (no post.md)")
        return False

    content = post_file.read_text(encoding="utf-8")
    fm, body = parse_front_matter(content)

    slug = post_dir.name
    title = fm.get("title", slug)
    post_date = fm.get("date", "2026-01-01")
    summary = fm.get("summary", "")
    tags = fm.get("tags", "")

    # Rewrite image paths: images/X.png -> {{ '/assets/images/{slug}/X.png' | relative_url }}
    body = re.sub(
        r'src="images/([^"]+)"',
        lambda m: "src=\"{{ '/assets/images/"
        + slug
        + "/"
        + m.group(1)
        + "' | relative_url }}\"",
        body,
    )

    # Build front matter with Jekyll requirements
    new_fm_lines = [
        "---",
        "layout: post",
        f'title: "{title}"',
        f"date: {post_date}",
    ]
    if summary:
        new_fm_lines.append(f'summary: "{summary}"')
    if tags:
        new_fm_lines.append(f"tags: [{tags}]")
    new_fm_lines.append(f"permalink: /blog/{post_date}/{slug}/")
    new_fm_lines.append("---")

    new_content = "\n".join(new_fm_lines) + "\n" + body

    # Write to _posts/
    out_name = f"{post_date}-{slug}.md"
    out_path = POSTS_DIR / out_name
    out_path.write_text(new_content, encoding="utf-8")

    # Copy images to assets/images/{slug}/
    images_dir = post_dir / "images"
    if images_dir.is_dir():
        img_files = list(images_dir.iterdir())
        if img_files:
            dest_dir = ASSETS_IMG_DIR / slug
            dest_dir.mkdir(parents=True, exist_ok=True)
            for img_file in img_files:
                if img_file.is_file():
                    shutil.copy2(img_file, dest_dir / img_file.name)

    print(f"  BUILT: {post_dir.name} -> _posts/{out_name}")
    return True


def clean_generated():
    """Remove previously generated post files from _posts/ and their images from assets/images/."""
    # Find posts that were generated by this build system (have a slug matching blog/ folders)
    blog_slugs = {
        d.name for d in BLOG_DIR.iterdir() if d.is_dir() and (d / "post.md").exists()
    }

    removed = 0
    for post_file in POSTS_DIR.glob("*.md"):
        content = post_file.read_text(encoding="utf-8")
        if "layout: post" in content:
            for slug in blog_slugs:
                if slug in post_file.name:
                    post_file.unlink()
                    removed += 1
                    break

    for slug in blog_slugs:
        img_dir = ASSETS_IMG_DIR / slug
        if img_dir.is_dir():
            shutil.rmtree(img_dir)
            removed += 1

    if removed:
        print(f"Cleaned {removed} generated files")
    return removed


def main():
    parser = argparse.ArgumentParser(description="Build blog posts for Jekyll")
    parser.add_argument(
        "--clean", action="store_true", help="Clean old generated files first"
    )
    args = parser.parse_args()

    if not BLOG_DIR.exists():
        print(
            f"Error: {BLOG_DIR} does not exist. Create it first with scripts/new-post.py"
        )
        sys.exit(1)

    POSTS_DIR.mkdir(parents=True, exist_ok=True)
    ASSETS_IMG_DIR.mkdir(parents=True, exist_ok=True)

    if args.clean:
        clean_generated()

    post_dirs = sorted(
        d for d in BLOG_DIR.iterdir() if d.is_dir() and (d / "post.md").exists()
    )

    if not post_dirs:
        print(
            'No posts found in blog/. Create one with: python scripts/new-post.py "Title"'
        )
        sys.exit(0)

    print(f"Building {len(post_dirs)} post(s)...")
    for post_dir in post_dirs:
        build_post(post_dir)

    print("\nDone! Preview with: .\\scripts\\local-jekyll-preview.ps1")


if __name__ == "__main__":
    main()
